### ISSUE TITLE
Support FreeRADIUS 3

### ISSUE THREAD

**Issue by plettich** [privacyidea/FreeRADIUS#11]
there are some issues getting this to work with FreeRADIUS 3 (default on debian 9.4).
My changes:
- The  `$raddbdir/sites-enabled/privacyidea`-file: 
```
server {
        authorize {
                files
                perl
                if (ok || updated) {
                        update control {
                                Auth-Type := Perl
                        }
                }
        }
        listen {
                type = auth
                ipaddr = *
                port = 0
        }
        authenticate {
                Auth-Type Perl {
                        perl
                }
        }
}
```
- The `$raddbdir/mods-enabled/perl`-file:
```
perl {
        filename = ${modconfdir}/${.:instance}/privacyidea.pl
}
```
- Copy the `privacyidea_radius.pm`-file into `$raddbdir/mods-config/perl/privacyidea.pl`
- Update the `$raddbdir/dictionary`-file

I also removed all other enabled sites.
On debian 9.4 you also need to remove the `libjson-xs-perl`-package since it breaks when running in threaded mode: https://cygwin.com/ml/cygwin/2016-03/msg00033.html
Radius still complains about `$RAD_REPLY{'Class'}` not being defined but the request goes through.
Oh, and use `User-Password=...` for `radclient` instead of just `Password=...`.

**Comment by cornelinux** [comment]
@plettich I think we support freeradius 3 now. The centos packages and UCS packages build that way.
So the issue could be closed, right? Or is it more of a packaging issue, so it should be move to another repo?

**Comment by cornelinux** [comment]
I suggest to add two directories with the corresponding config:

freeradius2/privacyidea
freeradius3/privacyidea

**Comment by cornelinux** [comment]
OK, working on packaging for FreeRADIUS2 / Ubuntu 18.04
