### ISSUE TITLE
privacyIDEA FreeRADIUS plugin doesnt respect proxy env vars

### ISSUE THREAD

**Issue by splashx** [privacyidea/FreeRADIUS#2]
For environment using `*_proxy` it's enough to add:

```
$ua->env_proxy;
```

At [this line](https://github.com/privacyidea/FreeRADIUS/blob/master/privacyidea_radius.pm#L354) according to the official documentation of [UserAgent](https://metacpan.org/pod/LWP::UserAgent#PROXY-ATTRIBUTES)

**Comment by cornelinux** [comment]
Thanks a lot!
Closed by your PR #3
