### ISSUE TITLE
All authentication requests are rejected when using default config

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/FreeRADIUS#34]
See the debug log at https://community.privacyidea.org/t/radius-config-file-not-found-could-not-parse-response/1092
in particular:
```
rlm_perl: privacyIDEA access granted
rlm_perl: Can not parse response from privacyIDEA.
```

I guess when running with the default config, the plugin rejects the request even though privacyIDEA approves it because the plugin crashes here:
https://github.com/privacyidea/FreeRADIUS/blob/b71bf503650c18c640cf9ee08cf758395b7de64d/privacyidea_radius.pm#L245
because the default config has no attribute ``Groups``

**Comment by plettich** [comment]
We can check if we have a valid config file file before applying the mapping.
