### ISSUE TITLE
change VSA

### ISSUE THREAD

**Issue by kileurf** [privacyidea/FreeRADIUS#6]
Hello,

i would like to know if it's possible to change the VSA send back to the radius server ?

For the moment it's the  privacyIDEA-Serial but i would like to send another VSA (fortinet dictionnary VSA)

**Comment by cornelinux** [comment]
Yes it is.
You can map the return details to Vendor Attributes.
https://github.com/privacyidea/FreeRADIUS/blob/master/rlm_perl.ini

**Comment by kileurf** [comment]
Can you explain me which parameter i need to change, i add dictionnary.fortinet and i include it to my dictionnary

and i change the rlm_perl.ini "[mapping]"

the name of the vendor Attribute change but not the attribute

thanks in advance for you're help

**Comment by cornelinux** [comment]
Hi,
I added some more information to the docs:
https://github.com/privacyidea/privacyidea/blob/master/doc/application_plugins/radius.rst#mapping-privacyidea-return-values-to-radius-attribute-value-pairs

**Comment by kileurf** [comment]
Thank you for you're help :)
